### ISSUE TITLE
It buffers, which makes it lose all the benefits of streams

### ISSUE THREAD

**Issue by GrosSacASac** [goto-bus-stop/html-minify-stream#14]

**Comment by goto-bus-stop** [comment]
That's correct. The purpose of this package is to support minifying in a chain of streams, so it's about the API contract not about efficiency.

If there is already a high quality streaming minifier, I would love to switch to it, but I'm not aware of any.

**Comment by GrosSacASac** [comment]
I started tinkering on a streaming html minifier https://github.com/GrosSacASac/stream-sac/blob/main/source/html/HtmlMinifier.js

What do you think ?
